### ISSUE TITLE
my phone can not find the net

### ISSUE THREAD

**Issue by rosickey** [flytreeleft/adhoc#1]
ubuntu 10.10 Notebook

~ifconfig

eth0 
    ...  
    Interrupt:16
eth1  
    ....
    Hardware address 00:16:6f:ad:xx:xx
    Interrupt:17 Memory:b0018000-b0018fff 

~sudo ./adhoc eth1 restart
Now, resart ad-hoc ...
Stopping adhoc ...
......
Wifi ad-hoc now stopped
Starting Ad-hoc...
Setting eth1 gateway[192.168.2.254] and netmask[255.255.255.0]...    [ GOOD ]
Setting down eth1...    [ GOOD ]
Setting eth1 mode[ad-hoc]...    [ GOOD ]
Setting eth1 essid[WiFi-Network]...    [ GOOD ]
Setting eth1 cannel[auto]...    [ FAILED ]
Setting eth1 key type[off]...    [ WARNING, non-encrypted network ]
Setting up eth1...    [ GOOD ]
Setting iptable...    [ GOOD ]
Completed!^^

my phone can not find the net

**Comment by flytreeleft** [comment]
It looks like that setting `channel` of eth1 to `auto` failed. You should try to found why it happended with running command `iwconfig eth1 channel auto`

**Comment by lingceng** [comment]
same problem with <b>rosickey</b> 
$ sudo iwconfig eth1 channel auto
Error for wireless request "Set Frequency" (8B04) :
    SET failed on device eth1 ; Invalid argument.

seems like a driver problem.

I can set up adhoc when using  win7 by typing <b>start network...</b>, but can't find the way to set on ubuntu12.10.

**Comment by flytreeleft** [comment]
@lingceng Hum, I think there is no enough information to find the reason for me. You can run commands following this: `sudo ifconfig eth1` and `sudo iwconfig eth1`, then paste the output information for me. Or you can have a try following [Ubuntu 12.04下设置笔记本成为wifi热点](http://qing.weibo.com/tj/570d75c633001aav.html). I just want to know whether your wireless device does work or not.

**Comment by lingceng** [comment]
@flytreeleft Thank you for reply. I have tried a similar guide, just something wrong with step 2, no <b>adhoc mode</b> at all. 

following is the output for ifconfig.

<pre>
$ sudo ifconfig eth1
[sudo] password for lingceng: 
eth1      Link encap:Ethernet  HWaddr e4:d5:3d:f3:ae:1b  
          inet addr:192.168.1.100  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::e6d5:3dff:fef3:ae1b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:34724 errors:0 dropped:0 overruns:0 frame:56454
          TX packets:31786 errors:35 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:29565384 (29.5 MB)  TX bytes:5855610 (5.8 MB)
          Interrupt:19 
$ sudo ifconfig eth0
eth0      Link encap:Ethernet  HWaddr 24:b6:fd:18:19:f6  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:43 Base address:0x4000 
</pre>

**Comment by flytreeleft** [comment]
Maybe there is something wrong with your driver, if you can set up access point in Win7. 

You can reinstall driver with running command:
`sudo apt-get install --reinstall firmware-iwlwifi`

Or read this blog [Linux: Find Wireless Driver Chipset Information](http://www.cyberciti.biz/faq/linux-find-wireless-driver-chipset/) to get more information of your driver.

Absolutely, you should make sure that your wireless device supports WiFi first.

**Comment by lingceng** [comment]
@flytreeleft 
I have done as the blog guide. <code>Capabilities:&lt;access denied&gt;</code> may tell the answer. Did not reinstall the driver for being unsure about the command.

<pre>
$ lspci
09:00.0 Network controller: Broadcom Corporation BCM4313 802.11b/g/n Wireless LAN Controller (rev 01)
$ lspci -vv -s 09:00.0
09:00.0 Network controller: Broadcom Corporation BCM4313 802.11b/g/n Wireless LAN Controller (rev 01)
    Subsystem: Dell Device 0012
    Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
    Latency: 0, Cache Line Size: 64 bytes
    Interrupt: pin A routed to IRQ 19
    Region 0: Memory at f7d00000 (64-bit, non-prefetchable) [size=16K]
    Capabilities: &lt;access denied&gt;
    Kernel driver in use: wl
    Kernel modules: wl, bcma, brcmsmac
$ modinfo wl
filename:       /lib/modules/3.2.0-31-generic-pae/updates/dkms/wl.ko
license:        MIXED/Proprietary
srcversion:     D9C86A9C5C3D22E103EF402
alias:          pci:v000014E4d00000576sv*sd*bc*sc*i*
alias:          pci:v000014E4d0000435Asv*sd*bc*sc*i*
alias:          pci:v000014E4d00004359sv*sd*bc*sc*i*
alias:          pci:v000014E4d00004358sv*sd*bc*sc*i*
alias:          pci:v000014E4d00004727sv*sd*bc*sc*i*
alias:          pci:v000014E4d00004357sv*sd*bc*sc*i*
alias:          pci:v000014E4d0000A99Dsv*sd*bc*sc*i*
alias:          pci:v000014E4d00004353sv*sd*bc*sc*i*
alias:          pci:v000014E4d0000432Dsv*sd*bc*sc*i*
alias:          pci:v000014E4d0000432Csv*sd*bc*sc*i*
alias:          pci:v000014E4d0000432Bsv*sd*bc*sc*i*
alias:          pci:v000014E4d0000432Asv*sd*bc*sc*i*
alias:          pci:v000014E4d00004329sv*sd*bc*sc*i*
alias:          pci:v000014E4d00004328sv*sd*bc*sc*i*
alias:          pci:v000014E4d00004315sv*sd*bc*sc*i*
alias:          pci:v000014E4d00004313sv*sd*bc*sc*i*
alias:          pci:v000014E4d00004312sv*sd*bc*sc*i*
alias:          pci:v000014E4d00004311sv*sd*bc*sc*i*
depends:        lib80211
vermagic:       3.2.0-31-generic-pae SMP mod_unload modversions 686 
parm:           oneonly:int
parm:           piomode:int
parm:           instance_base:int
parm:           nompc:int
parm:           name:string
</pre>

**Comment by flytreeleft** [comment]
Hum, I have the same value of `Capabilities`. I recommend you to reinstall the driver following http://wiki.debian.org/wl and [How do I get a Broadcom BCM4313 wireless card working?](http://askubuntu.com/questions/127633/how-do-i-get-a-broadcom-bcm4313-wireless-card-working). Maybe that will work.
